// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/category"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/pet"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/predicate"
	"github.com/lrstanley/entrest/_examples/kitchensink/internal/database/ent/user"
)

// PetUpdate is the builder for updating Pet entities.
type PetUpdate struct {
	config
	hooks    []Hook
	mutation *PetMutation
}

// Where appends a list predicates to the PetUpdate builder.
func (_u *PetUpdate) Where(ps ...predicate.Pet) *PetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PetUpdate) SetName(v string) *PetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PetUpdate) SetNillableName(v *string) *PetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNicknames sets the "nicknames" field.
func (_u *PetUpdate) SetNicknames(v []string) *PetUpdate {
	_u.mutation.SetNicknames(v)
	return _u
}

// AppendNicknames appends value to the "nicknames" field.
func (_u *PetUpdate) AppendNicknames(v []string) *PetUpdate {
	_u.mutation.AppendNicknames(v)
	return _u
}

// ClearNicknames clears the value of the "nicknames" field.
func (_u *PetUpdate) ClearNicknames() *PetUpdate {
	_u.mutation.ClearNicknames()
	return _u
}

// SetAge sets the "age" field.
func (_u *PetUpdate) SetAge(v int) *PetUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *PetUpdate) SetNillableAge(v *int) *PetUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *PetUpdate) AddAge(v int) *PetUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PetUpdate) SetType(v pet.Type) *PetUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PetUpdate) SetNillableType(v *pet.Type) *PetUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *PetUpdate) AddCategoryIDs(ids ...int) *PetUpdate {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *PetUpdate) AddCategories(v ...*Category) *PetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *PetUpdate) SetOwnerID(id uuid.UUID) *PetUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *PetUpdate) SetNillableOwnerID(id *uuid.UUID) *PetUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PetUpdate) SetOwner(v *User) *PetUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddFriendIDs adds the "friends" edge to the Pet entity by IDs.
func (_u *PetUpdate) AddFriendIDs(ids ...int) *PetUpdate {
	_u.mutation.AddFriendIDs(ids...)
	return _u
}

// AddFriends adds the "friends" edges to the Pet entity.
func (_u *PetUpdate) AddFriends(v ...*Pet) *PetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendIDs(ids...)
}

// AddFollowedByIDs adds the "followed_by" edge to the User entity by IDs.
func (_u *PetUpdate) AddFollowedByIDs(ids ...uuid.UUID) *PetUpdate {
	_u.mutation.AddFollowedByIDs(ids...)
	return _u
}

// AddFollowedBy adds the "followed_by" edges to the User entity.
func (_u *PetUpdate) AddFollowedBy(v ...*User) *PetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFollowedByIDs(ids...)
}

// Mutation returns the PetMutation object of the builder.
func (_u *PetUpdate) Mutation() *PetMutation {
	return _u.mutation
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *PetUpdate) ClearCategories() *PetUpdate {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *PetUpdate) RemoveCategoryIDs(ids ...int) *PetUpdate {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *PetUpdate) RemoveCategories(v ...*Category) *PetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PetUpdate) ClearOwner() *PetUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearFriends clears all "friends" edges to the Pet entity.
func (_u *PetUpdate) ClearFriends() *PetUpdate {
	_u.mutation.ClearFriends()
	return _u
}

// RemoveFriendIDs removes the "friends" edge to Pet entities by IDs.
func (_u *PetUpdate) RemoveFriendIDs(ids ...int) *PetUpdate {
	_u.mutation.RemoveFriendIDs(ids...)
	return _u
}

// RemoveFriends removes "friends" edges to Pet entities.
func (_u *PetUpdate) RemoveFriends(v ...*Pet) *PetUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendIDs(ids...)
}

// ClearFollowedBy clears all "followed_by" edges to the User entity.
func (_u *PetUpdate) ClearFollowedBy() *PetUpdate {
	_u.mutation.ClearFollowedBy()
	return _u
}

// RemoveFollowedByIDs removes the "followed_by" edge to User entities by IDs.
func (_u *PetUpdate) RemoveFollowedByIDs(ids ...uuid.UUID) *PetUpdate {
	_u.mutation.RemoveFollowedByIDs(ids...)
	return _u
}

// RemoveFollowedBy removes "followed_by" edges to User entities.
func (_u *PetUpdate) RemoveFollowedBy(v ...*User) *PetUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFollowedByIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetUpdate) check() error {
	if v, ok := _u.mutation.Age(); ok {
		if err := pet.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "Pet.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := pet.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Pet.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pet.Table, pet.Columns, sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nicknames(); ok {
		_spec.SetField(pet.FieldNicknames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNicknames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pet.FieldNicknames, value)
		})
	}
	if _u.mutation.NicknamesCleared() {
		_spec.ClearField(pet.FieldNicknames, field.TypeJSON)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(pet.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(pet.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pet.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendsIDs(); len(nodes) > 0 && !_u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFollowedByIDs(); len(nodes) > 0 && !_u.mutation.FollowedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PetUpdateOne is the builder for updating a single Pet entity.
type PetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PetMutation
}

// SetName sets the "name" field.
func (_u *PetUpdateOne) SetName(v string) *PetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableName(v *string) *PetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNicknames sets the "nicknames" field.
func (_u *PetUpdateOne) SetNicknames(v []string) *PetUpdateOne {
	_u.mutation.SetNicknames(v)
	return _u
}

// AppendNicknames appends value to the "nicknames" field.
func (_u *PetUpdateOne) AppendNicknames(v []string) *PetUpdateOne {
	_u.mutation.AppendNicknames(v)
	return _u
}

// ClearNicknames clears the value of the "nicknames" field.
func (_u *PetUpdateOne) ClearNicknames() *PetUpdateOne {
	_u.mutation.ClearNicknames()
	return _u
}

// SetAge sets the "age" field.
func (_u *PetUpdateOne) SetAge(v int) *PetUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableAge(v *int) *PetUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *PetUpdateOne) AddAge(v int) *PetUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PetUpdateOne) SetType(v pet.Type) *PetUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PetUpdateOne) SetNillableType(v *pet.Type) *PetUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (_u *PetUpdateOne) AddCategoryIDs(ids ...int) *PetUpdateOne {
	_u.mutation.AddCategoryIDs(ids...)
	return _u
}

// AddCategories adds the "categories" edges to the Category entity.
func (_u *PetUpdateOne) AddCategories(v ...*Category) *PetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *PetUpdateOne) SetOwnerID(id uuid.UUID) *PetUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *PetUpdateOne) SetNillableOwnerID(id *uuid.UUID) *PetUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *PetUpdateOne) SetOwner(v *User) *PetUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddFriendIDs adds the "friends" edge to the Pet entity by IDs.
func (_u *PetUpdateOne) AddFriendIDs(ids ...int) *PetUpdateOne {
	_u.mutation.AddFriendIDs(ids...)
	return _u
}

// AddFriends adds the "friends" edges to the Pet entity.
func (_u *PetUpdateOne) AddFriends(v ...*Pet) *PetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendIDs(ids...)
}

// AddFollowedByIDs adds the "followed_by" edge to the User entity by IDs.
func (_u *PetUpdateOne) AddFollowedByIDs(ids ...uuid.UUID) *PetUpdateOne {
	_u.mutation.AddFollowedByIDs(ids...)
	return _u
}

// AddFollowedBy adds the "followed_by" edges to the User entity.
func (_u *PetUpdateOne) AddFollowedBy(v ...*User) *PetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFollowedByIDs(ids...)
}

// Mutation returns the PetMutation object of the builder.
func (_u *PetUpdateOne) Mutation() *PetMutation {
	return _u.mutation
}

// ClearCategories clears all "categories" edges to the Category entity.
func (_u *PetUpdateOne) ClearCategories() *PetUpdateOne {
	_u.mutation.ClearCategories()
	return _u
}

// RemoveCategoryIDs removes the "categories" edge to Category entities by IDs.
func (_u *PetUpdateOne) RemoveCategoryIDs(ids ...int) *PetUpdateOne {
	_u.mutation.RemoveCategoryIDs(ids...)
	return _u
}

// RemoveCategories removes "categories" edges to Category entities.
func (_u *PetUpdateOne) RemoveCategories(v ...*Category) *PetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryIDs(ids...)
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *PetUpdateOne) ClearOwner() *PetUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearFriends clears all "friends" edges to the Pet entity.
func (_u *PetUpdateOne) ClearFriends() *PetUpdateOne {
	_u.mutation.ClearFriends()
	return _u
}

// RemoveFriendIDs removes the "friends" edge to Pet entities by IDs.
func (_u *PetUpdateOne) RemoveFriendIDs(ids ...int) *PetUpdateOne {
	_u.mutation.RemoveFriendIDs(ids...)
	return _u
}

// RemoveFriends removes "friends" edges to Pet entities.
func (_u *PetUpdateOne) RemoveFriends(v ...*Pet) *PetUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendIDs(ids...)
}

// ClearFollowedBy clears all "followed_by" edges to the User entity.
func (_u *PetUpdateOne) ClearFollowedBy() *PetUpdateOne {
	_u.mutation.ClearFollowedBy()
	return _u
}

// RemoveFollowedByIDs removes the "followed_by" edge to User entities by IDs.
func (_u *PetUpdateOne) RemoveFollowedByIDs(ids ...uuid.UUID) *PetUpdateOne {
	_u.mutation.RemoveFollowedByIDs(ids...)
	return _u
}

// RemoveFollowedBy removes "followed_by" edges to User entities.
func (_u *PetUpdateOne) RemoveFollowedBy(v ...*User) *PetUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFollowedByIDs(ids...)
}

// Where appends a list predicates to the PetUpdate builder.
func (_u *PetUpdateOne) Where(ps ...predicate.Pet) *PetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PetUpdateOne) Select(field string, fields ...string) *PetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pet entity.
func (_u *PetUpdateOne) Save(ctx context.Context) (*Pet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PetUpdateOne) SaveX(ctx context.Context) *Pet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PetUpdateOne) check() error {
	if v, ok := _u.mutation.Age(); ok {
		if err := pet.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "Pet.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := pet.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Pet.type": %w`, err)}
		}
	}
	return nil
}

func (_u *PetUpdateOne) sqlSave(ctx context.Context) (_node *Pet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pet.Table, pet.Columns, sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pet.FieldID)
		for _, f := range fields {
			if !pet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nicknames(); ok {
		_spec.SetField(pet.FieldNicknames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNicknames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, pet.FieldNicknames, value)
		})
	}
	if _u.mutation.NicknamesCleared() {
		_spec.ClearField(pet.FieldNicknames, field.TypeJSON)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(pet.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(pet.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pet.FieldType, field.TypeEnum, value)
	}
	if _u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoriesIDs(); len(nodes) > 0 && !_u.mutation.CategoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.CategoriesTable,
			Columns: pet.CategoriesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pet.OwnerTable,
			Columns: []string{pet.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendsIDs(); len(nodes) > 0 && !_u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   pet.FriendsTable,
			Columns: pet.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pet.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FollowedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFollowedByIDs(); len(nodes) > 0 && !_u.mutation.FollowedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FollowedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   pet.FollowedByTable,
			Columns: pet.FollowedByPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FollowsCreate{config: _u.config, mutation: newFollowsMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Pet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
