// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/entrest/_examples/kitchensink/database/ent/predicate"
	"github.com/lrstanley/entrest/_examples/kitchensink/database/ent/settings"
	"github.com/lrstanley/entrest/_examples/kitchensink/database/ent/user"
)

// SettingsUpdate is the builder for updating Settings entities.
type SettingsUpdate struct {
	config
	hooks    []Hook
	mutation *SettingsMutation
}

// Where appends a list predicates to the SettingsUpdate builder.
func (su *SettingsUpdate) Where(ps ...predicate.Settings) *SettingsUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SettingsUpdate) SetUpdatedAt(t time.Time) *SettingsUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetGlobalBanner sets the "global_banner" field.
func (su *SettingsUpdate) SetGlobalBanner(s string) *SettingsUpdate {
	su.mutation.SetGlobalBanner(s)
	return su
}

// SetNillableGlobalBanner sets the "global_banner" field if the given value is not nil.
func (su *SettingsUpdate) SetNillableGlobalBanner(s *string) *SettingsUpdate {
	if s != nil {
		su.SetGlobalBanner(*s)
	}
	return su
}

// ClearGlobalBanner clears the value of the "global_banner" field.
func (su *SettingsUpdate) ClearGlobalBanner() *SettingsUpdate {
	su.mutation.ClearGlobalBanner()
	return su
}

// AddAdminIDs adds the "admins" edge to the User entity by IDs.
func (su *SettingsUpdate) AddAdminIDs(ids ...int) *SettingsUpdate {
	su.mutation.AddAdminIDs(ids...)
	return su
}

// AddAdmins adds the "admins" edges to the User entity.
func (su *SettingsUpdate) AddAdmins(u ...*User) *SettingsUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.AddAdminIDs(ids...)
}

// Mutation returns the SettingsMutation object of the builder.
func (su *SettingsUpdate) Mutation() *SettingsMutation {
	return su.mutation
}

// ClearAdmins clears all "admins" edges to the User entity.
func (su *SettingsUpdate) ClearAdmins() *SettingsUpdate {
	su.mutation.ClearAdmins()
	return su
}

// RemoveAdminIDs removes the "admins" edge to User entities by IDs.
func (su *SettingsUpdate) RemoveAdminIDs(ids ...int) *SettingsUpdate {
	su.mutation.RemoveAdminIDs(ids...)
	return su
}

// RemoveAdmins removes "admins" edges to User entities.
func (su *SettingsUpdate) RemoveAdmins(u ...*User) *SettingsUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.RemoveAdminIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SettingsUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SettingsUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SettingsUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SettingsUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SettingsUpdate) check() error {
	if v, ok := su.mutation.GlobalBanner(); ok {
		if err := settings.GlobalBannerValidator(v); err != nil {
			return &ValidationError{Name: "global_banner", err: fmt.Errorf(`ent: validator failed for field "Settings.global_banner": %w`, err)}
		}
	}
	return nil
}

func (su *SettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.GlobalBanner(); ok {
		_spec.SetField(settings.FieldGlobalBanner, field.TypeString, value)
	}
	if su.mutation.GlobalBannerCleared() {
		_spec.ClearField(settings.FieldGlobalBanner, field.TypeString)
	}
	if su.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !su.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SettingsUpdateOne is the builder for updating a single Settings entity.
type SettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SettingsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SettingsUpdateOne) SetUpdatedAt(t time.Time) *SettingsUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetGlobalBanner sets the "global_banner" field.
func (suo *SettingsUpdateOne) SetGlobalBanner(s string) *SettingsUpdateOne {
	suo.mutation.SetGlobalBanner(s)
	return suo
}

// SetNillableGlobalBanner sets the "global_banner" field if the given value is not nil.
func (suo *SettingsUpdateOne) SetNillableGlobalBanner(s *string) *SettingsUpdateOne {
	if s != nil {
		suo.SetGlobalBanner(*s)
	}
	return suo
}

// ClearGlobalBanner clears the value of the "global_banner" field.
func (suo *SettingsUpdateOne) ClearGlobalBanner() *SettingsUpdateOne {
	suo.mutation.ClearGlobalBanner()
	return suo
}

// AddAdminIDs adds the "admins" edge to the User entity by IDs.
func (suo *SettingsUpdateOne) AddAdminIDs(ids ...int) *SettingsUpdateOne {
	suo.mutation.AddAdminIDs(ids...)
	return suo
}

// AddAdmins adds the "admins" edges to the User entity.
func (suo *SettingsUpdateOne) AddAdmins(u ...*User) *SettingsUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.AddAdminIDs(ids...)
}

// Mutation returns the SettingsMutation object of the builder.
func (suo *SettingsUpdateOne) Mutation() *SettingsMutation {
	return suo.mutation
}

// ClearAdmins clears all "admins" edges to the User entity.
func (suo *SettingsUpdateOne) ClearAdmins() *SettingsUpdateOne {
	suo.mutation.ClearAdmins()
	return suo
}

// RemoveAdminIDs removes the "admins" edge to User entities by IDs.
func (suo *SettingsUpdateOne) RemoveAdminIDs(ids ...int) *SettingsUpdateOne {
	suo.mutation.RemoveAdminIDs(ids...)
	return suo
}

// RemoveAdmins removes "admins" edges to User entities.
func (suo *SettingsUpdateOne) RemoveAdmins(u ...*User) *SettingsUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.RemoveAdminIDs(ids...)
}

// Where appends a list predicates to the SettingsUpdate builder.
func (suo *SettingsUpdateOne) Where(ps ...predicate.Settings) *SettingsUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SettingsUpdateOne) Select(field string, fields ...string) *SettingsUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Settings entity.
func (suo *SettingsUpdateOne) Save(ctx context.Context) (*Settings, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SettingsUpdateOne) SaveX(ctx context.Context) *Settings {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SettingsUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SettingsUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := settings.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SettingsUpdateOne) check() error {
	if v, ok := suo.mutation.GlobalBanner(); ok {
		if err := settings.GlobalBannerValidator(v); err != nil {
			return &ValidationError{Name: "global_banner", err: fmt.Errorf(`ent: validator failed for field "Settings.global_banner": %w`, err)}
		}
	}
	return nil
}

func (suo *SettingsUpdateOne) sqlSave(ctx context.Context) (_node *Settings, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(settings.Table, settings.Columns, sqlgraph.NewFieldSpec(settings.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Settings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, settings.FieldID)
		for _, f := range fields {
			if !settings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != settings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(settings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.GlobalBanner(); ok {
		_spec.SetField(settings.FieldGlobalBanner, field.TypeString, value)
	}
	if suo.mutation.GlobalBannerCleared() {
		_spec.ClearField(settings.FieldGlobalBanner, field.TypeString)
	}
	if suo.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedAdminsIDs(); len(nodes) > 0 && !suo.mutation.AdminsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.AdminsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   settings.AdminsTable,
			Columns: []string{settings.AdminsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Settings{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{settings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
