name: docs

on:
  pull_request:
    branches: [master]
    paths: ["docs/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths: ["docs/**"]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - run: make docs-build
      - if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist/
      - if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
